server:
  port: 8081

spring:
  cloud:
    config:
      import: "optional:configserver:"
  datasource:
    url: jdbc:postgresql://localhost:5432/authserverspring
    username: postgres
    password: souza673
  jpa:
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

auth:
  server:
    jwtSecret: ym^_3p4t#pcv_7oi0+6oyeef6vo&ees@w+@27o00vv4(cte@z
    jwtExpirationMs: 86400000

#logging.level.root=debug